# -*- coding: utf-8 -*-
"""Data Structures_Amalina.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C958nGM_JghhDhqZZIkCaIDqpIC1D0JH
"""

# Data Structures in Python
# A data structure is a way of organizing and storing data so it can be used efficiently.

# Why we need them
# They organize data in a structured way.
# They help store data efficiently.
# They make it easy to access and use data.
# They allow data to be managed easily, such as adding, removing, or searching.
# If we are using many data in one single variable, thats data stucture

# TYPE OF DATA STRUCTURE : LIST, TUPLE, SET, DICTIONARY, ARRAY, SERIES, DATAFRAME
#                                                       (    IN DATA SCIENCE     )
# LIST, TUPLE, SET, DICTIONARY

#LIST IN PYTHON
#LIST IS A DATA STRUCTURE USED TO STORE COLLECTION OF DATA VALUES
#LIST IS AN ITERABLE IN PYTHON
# *iterable is the data that can perform iteration (eg: string, list, dictionary)
#LIST IS AN ORDERED COLLECTION OF DATA VALUES
#LIST IS MUTABLE IN NATURE (the data can be remove, add, delete, modify, update)
#IN LIST WE CAN STORE MIXED DATA TYPE (EG: emp_info = [38, 'John', 28.3, true]<--LIST MUST USE SQUARE BRACKET OR list () eg: emp_info = list([38, 'John', 28.3, true])
#IN PYTHON LIST CAN BE DEFINED BY USING [] OR list()
#IN LIST WE CAN STORE DUPLICATE ELEMENTS

# CREATE A LIST

list1 = [10,20,30,40,50,60]
print (type(list1))

list2 = list(['a','b','c'])
print(type(list2))

#Empty list
list3 = []
print(type(list3))

#INDEXING AND SLICING (exam)
list1 = [10,20,30,40,50,60]

# 10  20  30  40  50  60
# 0   1   2   3   4   5
# -6  -5  -4  -3  -2  -1 <--backward/negative index

print (list1)
print (list1[3])
print (list1 [-1])
print (list1 [1:5])
print (list1 [1:5:2])
print (list1 [::-1])

# using for loop (iv question)
list1 = [10,20,30,40,50,60]
for i in list1:
  print (i)

# Using for loop print list elements along with their Index Number

# len(iterable/sequence)
# used to return the number of elements in a Sequence

list1 = [10,20,30,40,50,60]
print(len(list1))

# using for loop print list elements along with their Index Number

#Index 0 : 10
#Index 1 : 20
#Index 2 : 30

list1 = [10,20,30,40,50,60]
for i in list1:
  print (f'Index {0} : {i}') #---salah (buat sndri)

list1 = [10,20,30,40,50,60]
print (len(list1))

list1 = [10,20,30,40,50,60]
for i in range (len(list1)):
  print (f' Index {i} : {list1[i]}')

# using index() method
list1 = [10,20,30,40,50,60]
print (list1.index(30))

list1 = [10,20,30,40,50,60]
for i in list1:
  print (f'Index {list1.index(i)} : {i}')

# enumerate ()
# it's a built-in function used to return element with index numbers

list1 = [10,20,30,40,50,60]
for i in enumerate(list1):
  print (i)

list1 = [10,20,30,40,50,60]
for i,e in enumerate(list1): #i will iterate IndexNo. #e will iterate Elements
  print (f'Index {i} : {e}')

stInfo = [123, 'John', 32, 'Python', 78.21, True, True, True]
print (stInfo)

#LIST BUILT-IN METHODS
mylist = [10,20,30,40,50,60,70,80,90,100]
print ('Original List :', mylist)
print (f'Original list : {mylist}')

# a.) append(value)
#used to add a new element at the END of the list

mylist.append(200)
print ('After Append : ', mylist)

# b.) insert (indexNumber, value)
# used to add a new element at any SPECIFIC position in list

mylist.insert (4,400)
print ('After Insert : ', mylist)

#c.) pop (indexNumber)
# used to delete an elemen from the specified index number.

mylist.pop(1)
print ('After Pop :', mylist)

# d.) pop()
# used to delete the last element from list

mylist.pop()
print ('After Pop : ', mylist)

# e.) remove (value) *iv question
# used to removed the specified element from a list

mylist.remove(80)
print ('After Remove : ', mylist)

# if we try to delete an element which does not exist it will give an Error
# list = [10, 20, 30, 40, 10,10,10, 50, 60, 70]
# list.remove(10) <-- hanya the first element yg akan didelete, the 2nd,3rd and next 10 will not be removed
# it will delete the first occurance of the specified value

# f.) reverse()
mylist.reverse()
print ('After Reverse : ', mylist)

# g.) clear ()
# used to remove all elements from the list

# iv question (diff between clear and delete)
# clear used to remove all element from the list, delete used to delete the entire list
mylist.clear()
print ('After Clear : ', mylist)

# h.) delete keyword
del mylist

# i.) sort()

price = [56,20,12,90,87,45.32,18,10,37,29]
price.sort()  # by default it will in ascending order
print (price)

price = [56,20,12,90,87,45.32,18,10,37,29]
price.sort(reverse=True)  # descending order
print (price)

list1 = [10,20,10,30,40,10,10,50,60,10]
# delete all 10 from the list  *iv question

for i in list1:
  if i == 10:
    list1.remove (i)
print (list1)
# the last 10 does not deleted

list1 = [10,20,10,30,40,10,10,50,60,10]
while 10 in list1:
    list1.remove(10)
print(list1)

# Task 1
# list1 = [10,20,10,30,40,10,10,50,60,10]
# keep the second 10 only
# list1 = [20,10,30,40,50,60]

# Task 2
# list1 = [10,20,10,30,40,10,10,50,60,10]
# just delete second 10 only
# list1 = [10,20,30,40,10,10,50,60,10]

#TUPLE IN PYTHON
#TUPLE IS A DATA STRUCTURE USED TO STORE COLLECTION OF DATA VALUES
#TUPLE IS AN ITERABLE IN PYTHON
# *iterable is the data that can perform iteration (eg: string, list, dictionary)
#TUPLE IS AN ORDERED COLLECTION OF DATA VALUES
#TUPLE IS IMMUTABLE IN NATURE (the data canNOT be remove, add, delete, modify, update)
#IN TUPLE WE CAN STORE MIXED DATA TYPE (EG: emp_info = [38, 'John', 28.3, true]<--LIST MUST USE SQUARE BRACKET OR list () eg: emp_info = list([38, 'John', 28.3, true])
#IN PYTHON TUPLE CAN BE DEFINED BY USING () OR tuple()
#IN TUPLE WE CAN STORE DUPLICATE ELEMENTS

# CREATE A TUPLE

tupl1 = (10,20,30,40,50,60)
print(type(tupl1))

tupl2 = tuple((10,20,30,40,50,60))
print(type(tupl2))

tupl3 = ()
print(type(tupl3))

# iv question & pcep exam
myvar = 10, 'John', 90.21, True, [10,20,30]   # <-- if no square bracket, data type is tuple
print (type(myvar))

myvar = [10, 'John', 90.21, True, [10,20,30]]   # <--if use square bracket, jd list type
print (type(myvar))

# How to create a tuple having one element

tupl1 = (10)  # tkde coma, jd type integer
print (type(tupl1))

tupl1 = (10,) # ltk coma jd tuple type. mmg dh fixed in python programming
print (type(tupl1))

tupl1 = (10,)
print (tupl1[0])

# Tuple is Immutable
# use for data that can't be change/modify (eg: ic, bank acc num)
# utk data yg perlu change, like bank balance, age, use LIST, dont use tuple
# possible way to convert tuple into list -> type casting (but not recommended)
# list(tuple) <- not recommended

tupl = (10,20,30,40,50)
print (tupl)

tupl[2] = 300  #error, tkleh modify langsung
print(tupl)

tupl = (10,20,30,40,10,10,50,60,10,10,70,80)
# tuple hanya bole guna len, count , index.
#len()
print ('No of element : ', len(tupl))

#count(value)  --> it will count the occurance of specified value
print ('No of times 10 appears :', tupl.count(10))

# index(value)  --> it will get the index number of specified value
print ('Index No. of 70 :', tupl.index(70))

tupl = (10,20,30,40,10,10,50,60,10,10,70,80)
# sorted() function works on any iterable
# returns a new list of sorted elements
print(sorted(tupl))
print(sorted(tupl,reverse=True))

# SET IN PYTHON
# SET IS A DATA STRUCTURE USED TO STORE COLLECTION OF DATA VALUES
# SET IS AN ITERABLE IN PYTHON
# *iterable is the data that can perform iteration (eg: string, list, dictionary)
# SET IS AN UN-ORDERED COLLECTION OF DATA VALUES

#IN PYTHON SET CAN BE DEFINED BY USING {} OR set()
#IN SET WE CANNOT STORE DUPLICATE ELEMENTS

# CREATE A SET

set1 = {10,20,30,40}
print (type(set1))

set2 = set({10,20,30,40})
print (type(set2))

set3 = set()
print (type(set3))

set3 = {}  # <-- cannot use curly braces for blank set, it will become dictionary data structure, instead use set() like line 18
print (type(set3))

list1 = [10,20,30,40,50,60]
print (list1)

tupl1 = (10,20,30,40,50,60)
print (tupl1)

set1 = {10,20,30,40,50,60}  #set is an unordered collection of data elements, hence no indexing/slicing can be perform on set data struture
print (set1)

set1 = {10,20,30,40,50,60}  #set is an unordered collection of data elements, hence no indexing/slicing can be perform on set data struture
print (set1[1:3])

set1 = {10,20,10,50,10,30,40,50,60}  #set will not show same elements twice
print (set1)

mylist = {10,20,10,50,10,30,40,50,60}
# How many unique no. of elements we have in a list
# benefit : we can remove any duplicated elements in the data
# kekurangan : the result is not in order

print (set(mylist))
print (len(set(mylist)))

mylist = {10,20,10,30,30,40,50,60,40,10,10,30,60}
# How many unique no. of elements we have in a list (without using set data structure)

empty_list = []
for i in mylist:
  if i != empty_list:   # if 10 does not exist in empty_list, if True,
    empty_list.append(i)  # 10 will inserted in the empty_list
print(len(empty_list))

# install ordered-set
# An OrderedSet is a mutable data structure that is a hybrid of a list and a set.
# It remembers the order of its entries, and every entry has an index number
# that can be looked up.
# https://pypi.org/project/ordered-set/
# pip --> python installer package

!pip install ordered-set

from ordered_set import OrderedSet

# Using Set
set1 = {10,20,30,40,50,60,40,10,10,30,60}
print(set1)

# Using OrderedSet
set1 = OrderedSet([10,20,30,40,50,60,40,10,10,30,60])
print(set1)

str1 = 'abracadabra'

print ('Using Set', set (str1))
print ('Using OrderedSet', OrderedSet (str1))

# DICTIONARY
# USED TO STORE INFORMATION IN A KEY:VALUE PAIR FORMAT
# DICTIONARY IS DEFINED BY USING {} OR dict()
# DICTIONARY IS MUTABLE IN NATURE
# IN DICTIONARY KEY HAS TO BE UNIQUE, BUT VALUES CAN BE DUPLICATED <- key tkleh sama, value boleh sama

# emp_info = [123 , 'john' , 'IT' , 32 , 8900 , 'j@gmail.com' , 'Klang'] #<- LIST form,klu guna list, kita kena ingat index numb utk stiap element/data,
#                                                                                       guna dictionary xyah ingat index num utk stiap element sbb dh ada meaningful key utk gntikan index
emp_info = {'id':123 , 'name':'john' , 'dept':'IT' , 'age':32 , 'sal':8900 , 'email':'j@gmail.com' , 'city':'Klang'}

print(type(emp_info))
print(emp_info)
print(emp_info['name'])   # indexing ->[index] ganti dgn [key name], but in dict cannot perform slicing
print(emp_info['email'])  # 1st method to get the value
print(emp_info['sal'])
# get(keyname)
print(emp_info.get('age')) # 2nd method, built-in function only can be perform in dict

# add a new key:value pair
# dictionary add this new key:value pair at the END *klu nk add a new key:value pair in between or at beginning, make changes at the original dict

emp_info["country"] = "Malaysia"
print(emp_info)

# updating the value
emp_info["age"] = 34
print(emp_info)

# delete key:value pair
# pop(keyName)

emp_info.pop("country")
print(emp_info)

# updating the key  (iv quest) *but the weakness, the new updated key:value pair will be at the end of the dict,better make changes at the original dict
emp_info["salary"] = emp_info.pop("sal") # first return the value and delete this key
print(emp_info)

mydict = {2:4 , 3:9 , 4:16 , 5.0:25} #(iv q) #keyName x semestinya str, can be int, float, bool, but useless la sbb x guna klebihan dict
print(mydict)

emp_details = {'id':[101,102,103] , 'name':['John','Alex','Smith'],
               'dept':['HR','IT','FN']} #can store multiple data values, utk stiap keyName,buat dlm bentuk list
print(emp_details)
print(emp_details['name'])
print(emp_details['name'][1]) #meaning kita nak tau nama utk index 1

import pandas as pd
df = pd.DataFrame(emp_details)
df

emp_info = {"id":123 , "name":"john" , "dept":"IT" , "age":32 ,
            "sal":8900 , "email":"j@gmail.com" , "city":"klang"}

# normal for loop will print only Keys
for i in emp_info:
  print(i)

# to print values
for i in emp_info.values():
  print(i)

# to print keys and values together
for k,v in emp_info.items():  #avoid use enumerate in dict. Use items
  print(f'{k} : {v}')

# Task
# Taking subjects marks from a faculty

# ask how many marks faculty wish to insert    3
# insert marks1
# insert marks2
# insert marks3
# save these marks --> List

# inserted marks are
# marks 1 :
# marks 2 :
# marks 3 :

howManyMarks = int(input('Enter How Many Marks You Wish To Insert : '))  # 2
i = 1
marksList = []

while i <= howManyMarks:                                      # 1 <=2 (t)       2<=2(t)        3<=3)f
  marks = int(input(f'Enter Marks {i} : '))                  # marks 1 :        marks 2 :
  marksList.append(marks)                                    # [45]             [45,78]
  i += 1                                                    # i = 2             i = 3

print('\nInserted Marks Are : ')
for x in range(len(marksList)):                           #    x   range(len(marksList))   range(len(2))  0 1
  print(f'Marks {x+1} : {marksList[x]}')                   #   Marks 1 : marksList[0]

mark_total = int(input('How Many Marks Faculty Wish to Insert : ')) #buat sendiri
i = 1
inserted_marks = []

while i <= mark_total:
  mark = int(input(f'Insert Mark {i} : '))
  inserted_marks.append(mark)
  i = i + 1

print ('\nInserted Marks are : ')
for x in range(len(inserted_marks)):
  print (f'Mark {x+1} : {inserted_marks[x]}')