# -*- coding: utf-8 -*-
"""Functions_Amalina.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CwG34rMLom2Ysb5wWfQ80TqxFBcwMo-2
"""

# Functions In Python
# A function is a block of code which only runs when it is called.
# Functions provide better modularity for your application and a high degree of code reusing.
# Good thing about functions is that they are famous with several names. Different programming
# languages name them differently, for example, functions, methods, sub-routines, procedures, etc.
# Functions make your code cleaner and save you a lot of time.
# Python Functions stop us from writing the same logic various times.
# We can bind the logic in one function and then call the same repeatedly.

# Advantage of using function :

# In Python a function is defined using the def keyword

# Syntax
# def function_name():
#     code to be executed

# So, why should you learn to use functions?

# Here are 5 clear reasons:

# Avoid repetition (Don't Repeat Yourself – DRY)

# Make your code easier to read

# Easier to fix and debug

# Break complex problems into smaller parts

# Reuse code in different places or even in different programs

# function without parameter/arguments

# function definition
def greetUser():
  print ('Welcome User')

# function calling
greetUser()
greetUser()
greetUser()

# what is a parameter and what is an argument *iv quest

# funtion with parameter/arguments

# what is parameter
# a variable defined in a function definition is known as PARAMETER
# act as a placeholder

# function definition
def greetUser(name):    # name is a parameter
  print ('Welcome User :', name)

# function calling
greetUser('John')       # <-- we cannot call the function without putting the data
greetUser('Joshua')     # 'John'is an argument  # arguments supplies data to a function
                        # arguments are defined in function calling

def addition(a,b):
  print(f'Addition of {a} and {b} is {a+b}')

addition(10,30)
addition(20,70)

# Using a function predict the future career

def greetUser(name):
  print (f'Name : {name}')
  import random
  professions = ['doctor' , 'pilot' , 'police' , 'engineer' , 'housewife']
  random.choice(professions)

greetUser('Amalina')

import random
def predict_career(name):
  professions = ['doctor' , 'pilot' , 'police' , 'engineer' , 'housewife']
  print (f'Hi user {name} your predicted profession is {random.choice(professions)}')

predict_career('John')
predict_career('Alex')

# def a function to check whether the entered no. is Even or Odd

def checkEvenOdd():         #<-- jwpn sndiri
  num = int(input(('Please Enter a Number : ')))
  if num%2==0:
    print ('Even Number')
  else:
    print ('Odd Number')

checkEvenOdd()

def checkEvenOdd(n):    # <-- jwpn betul
  if n%2==0:
    print ('Even Number')
  else:
    print ('Odd Number')

num = int(input(('Please Enter a Number : ')))
checkEvenOdd(num)

num = int(input(('Please Enter a Number : ')))
checkEvenOdd(num)

# function with parameter and with return statement
# a function with return statement is used to return a value

def checkEvenOdd(n):
  return n%2==0

num = int(input(('Please Enter a Number : ')))
res = checkEvenOdd(num)

if res:
    print ('Even Number')
else:
    print ('Odd Number')

myList = [10,20,30,40,50,60,70]
# calculate the sum of a List
res = sum(myList)
print(res)

# check whether the string is palindrome or not
# madam madam
# nitin nitin
# yash hsay

def palindrome (p):     # <--buat sendiri
  return p[::] == p[::-1]

word = input ('Please enter any word : ')
res = palindrome (word)

if res:
    print ('Palindrome')
else:
    print ('Not Palindrome')

def strReverse(text):   # <--jwpn yash
  return text[::-1]

a = 'madamamalina'
res = strReverse(a)

if a == res:
  print('Palindrome String')
else:
  print('Not a Palindrome String')