# -*- coding: utf-8 -*-
"""FunctionsPart2_Amalina.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14SrQo8x2UdK4V1R3CooDLxDLYdtdrL1M
"""

# install gTTS (Google Text-to-Speech), a Python library
!pip install gTTS

def textToSpeech(user_input):
    from gtts import gTTS
    tts = gTTS(user_input)
    tts.save('output.mp3')

user_input = input('Enter Any Text : ')
textToSpeech(user_input)

# *args
# Lambda function  <--iv quest
# map()  <--iv quest
# filter()  <--iv quest

# *args
# is a special parameter that can handle any number of arguments

# *args  --> receive arguments as a TUPLE

def sumOfNumbers(*args):
  print(args)

sumOfNumbers(1,2,3,4,5,6,7,8)
sumOfNumbers(1,2,3)
sumOfNumbers(1)
sumOfNumbers(1,2,3,4,5,6)

def sumOfNumbers(*args):
  sum = 0
  for i in args:
    sum = sum + i
  print(sum)

sumOfNumbers(1,2,3,4,5,6,7,8)
sumOfNumbers(1,2,3)
sumOfNumbers(1)
sumOfNumbers(1,2,3,4,5,6)

# def a function printEvens(*args)

evenNum = []       #jwpn sendiri(silap sbb evenNum=[] ltk kt luar function, supposedly dlm fuction)
def printEvens(*args):
  for i in args:
    if i%2 ==0:
      evenNum.append(i)
  print(evenNum)


printEvens(10,13,11,12,16,17,21,24,26,55,54,70,99,31)
printEvens(10,13,11,12,16,17)
printEvens(1,2,3,4,5,6,7,8,9,10)

def printEvens(*args):    #jwpn yash
  for i in args:
    if i%2 ==0:
      print(i,end=' ')    #ltk space kt end tu spy result ada space
  print()

printEvens(10,13,11,12,16,17,21,24,26,55,54,70,99,31)
printEvens(10,13,11,12,16,17)
printEvens(1,2,3,4,5,6,7,8,9,10)

def printEvens(*args):     #jwpn yash guna list method
  evenNum = []
  for i in args:
    if i%2 ==0:
      evenNum.append(i)
  print(evenNum)

printEvens(10,13,11,12,16,17,21,24,26,55,54,70,99,31)
printEvens(10,13,11,12,16,17)
printEvens(1,2,3,4,5,6,7,8,9,10)

# pass statement
'''The pass statement
In Python, the pass is the keyword, which won.t do anything. Sometimes there is a
situation where we need to define a syntatically empty block. We can define that
block using the pass keyword.
When the interpreter finds a pass statement in the pogram, it returns no operation.
'''

def complicated_func():
    pass

def funct1():
  pass

def funct2():
  pass

def funct3():
  pass

list1 = [10,13,11,12,16,17,21,24,26,55,54,70,99,31]
# print even numbers
# without using a loop
# SOLUTION USING filter() by lambda

# Lambda / Anonymous function

'''
Python Anonymous/Lambda Function

Sometimes we need to declare a function without any name. The nameless property function is called an anonymous
function or lambda function.
The reason behind the using anonymous function is for instant use, that is, one-time usage.
Normal function is declared using the def function. Whereas the anonymous function is declared
using the lambda keyword.

Syntax of lambda function:
lambda argument_list:expression

When we define a function using the lambda keyword, the code is very concise
so that there is more readability in the code. A lambda function can have any
number of arguments but return only one value after expression evaluation.
'''
# A lambda function can have any number of arguments , but can only have one expression

def square(num):    #<-- normal function
  return num*num

print (square(5))
print (square(7))

# anonymous function is a function without any name
# anonymous function is defined using Lambda keyword

# syntax
# Lambda arguments:expression

(lambda num:num*num)(7)     #<-- lambda function

# a Lambda can take any number of arguments but can have only one Expression
                                                #(eg:a+b+c+d+e, cannot a+b+c+d+e and a*b*c*d*e
(lambda a,b,c,d,e:a+b+c+d+e)(1,2,3,4,5)

(lambda a,b,c,d,e:a+b+c+d+e and a*b*c*d*e)(1,2,3,4,5)     #<-- lambda akan pilih one expression shj utk execute

# any python normal function we can convert into Lambda

import random
professions = ['doctor','pilot','police','engineer','housewife']
(lambda p:random.choice(p))(professions)

import random
professions = ['doctor','pilot','police','engineer','housewife']

name = input ('Tell me your name : ')
print (f'{name} your predicted profession is {(lambda p:random.choice(p))(professions)}')

# why we should learn Lambda
# Lambda is important to learn if you wanted to use
# filter() or map()

# Lmbda can also be used when you wish to use your function only for one time
# i.e, one-time usage

# filter()
# used to return the filtered values
# it is used to return the values based on some conditions
# filter (function, sequence)

numbers = [10,13,11,12,16,17,21,24,26,55,54,70,99,31]
def isEven(num):
    return num%2==0
list(filter(isEven,numbers))

# filter is the one who will take care of the Iterations
# meaning in the First Iteration filter will pass 10 to the isEven(10) --> true
# in the Second Iteration filter will pass 13 to the isEven(13) --> false
# in the Third Iteration filter will pass 11 to the isEven(11) --> false
# in the forth Iteration filter will pass 12 to the isEven(12) --> true

numbers = [10,13,11,12,16,17,21,24,26,55,54,70,99,31] #iv quest:list even num without using loop
list(filter(lambda n:n%2==0,numbers))

# filter is the one who will take care of the Iterations
# meaning in the First Iteration filter will pass 10 to the lambda 10:10%2==0 --> true
# in the Second Iteration filter will pass 13 to the lambda 13:13%2==0 --> false
# in the Third Iteration filter will pass 11 to the lambda 11:11%2==0 --> false
# in the forth Iteration filter will pass 12 to the lambda 12:12%2==0) --> true
# fi;ter only store true data

# using filter please print those emp_names where names starts with A or a
emp_names = ['alex','smith','john','Alijah','ariah','mathews','amir','jamison','Aisyah']  #<--using normal function
def newNames(n):
  return n.startswith(('A','a'))
list(filter(newNames,emp_names))

emp_names = ['alex','smith','john','Alijah','ariah','mathews','amir','jamison','Aisyah']  #<--using lambda
list(filter(lambda n:n.startswith(('A','a')),emp_names))

# map()
# map() is used to apply some functionality to each and every individual element of a Sequence

nums = [1,2,3,4,5,6,7,8,9,10]
# create a new list showing me the square of all numbers
# [1,4,9,16,25,......]
squareNum = [n*n for n in nums] #<-- using nested list comprehension
print(squareNum)

nums = [1,2,3,4,5,6,7,8,9,10]
squareNum = []    #<-- using for loop
for n in nums:
  squareNum.append(n*n)
print(squareNum)

nums = [1,2,3,4,5,6,7,8,9,10]
list(map(lambda n:n*n,nums))    #<-- using lambda map

# map is the one who will take care of the Iterations
# meaning in the First Iteration map will pass 1 to the lambda 1:1*1 --> 1
# in the Second Iteration map will pass 2 to the lambda 2:2*2 --> 4