# -*- coding: utf-8 -*-
"""GuessANumberGame_Amalina.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10baBZkmWpil2MTNSqtUNjWYcLvGf7___
"""

# Guess a number game
# Objective : our machine will generate one random number
# we have to guess the number in 4 attempts

#SOLUTION:
import random
guessAttempt = 1

print('🧠 Guess A Number Game 🧠')
print('Enter Your Name')
name = input()
print(f'Welcome User {name} 😍')
print('I am thinking of a number between 1 and 13 🧐. Please Wait.....')
randomNum = random.randint(1,13)
print('Number Is Generated ✅ Guess The Number In 4 Attempts!')
while guessAttempt <= 4:
  print(f'Attempt{guessAttempt} Take A Guess.')
  guess = int(input())

  if guess == randomNum:
    print('🥳 Congratulation. Correct Guess 🥳')
    print(f'You have guess the number in {guessAttempt} attempt.')
    break

  if guess > randomNum:
    print('Your Guess Is Too HIGH ⬆️ Think Of A Smaller Number')

  if guess < randomNum:
    print('Your Guess Is Too LOW ⬇️ Think Of A Bigger Number')

  guessAttempt = guessAttempt + 1

if guess!=randomNum:
  print('🤯 GAME OVER! 🤯')
  print(f'The Correct Number Was {randomNum} 😜')