# -*- coding: utf-8 -*-
"""Loops_Amalina.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gLd1GBWAvPXwcA70aUqO5V-R64Q8iWBl
"""

# Loops

# Loops in Python are used to repeat a block of code multiple times without
# writing the same code again and again.

# Loops help us repeat tasks efficiently and smartly.

# A loop is a control structure that repeats a block of code until a condition is met.

# categories : for and while

# for loop
# for Loop is used to iterate over a Sequence [collection of data values]

# syntax
# for iterable_variable in Sequence:
#   block of code

# AFTER EVERY ITERATION BODY OF FOR LOOP
# WILL BE EXECUTED

for i in "Python":
  print (i)

for i in ('Python , Network'):
  print (i)

for i in ('Python','Network'):
  print (i)

txt = ('Python' , 'Network')
for i in txt:
  print (i)

product_prices = 10 , 13 , 15 , 16 , 18 , 21 , 23 , 24 , 25 , 27 , 30 , 32 , 34 , 35 , 40 , 43 , 45 , 47 , 48 , 50 , 51 , 52 , 53
tax = 2.05

for i in product_prices:
  print (i + tax)

numbers = 10 , 13 , 15 , 16 , 18 , 21 , 23 , 24 , 25 , 27 , 30 , 32 , 34 , 35 , 40 , 43 , 45 , 47 , 48 , 50 , 51 , 52 , 53
# print only the even numbers

for i in numbers:
  if i%2==0:
    print (i)

emp_names = 'Alex' , 'John' , 'Smith' , 'amir' , 'Tina' , 'mathews' , 'Anders' , 'Juliet' , 'Allan' , 'ashley'

# print only those names where the first letter startswith 'A' or 'a'

#METHOD 1   <-- not recommended, traditional way
for x in emp_names:
  if x [0] == 'A' or x [0] == 'a':    #USING INDEXING
    print (x)

#METHOD 2   <-- better approach
for x in emp_names:
  if x.startswith(('A','a')):   #USING startswith()
    print (x)

# range()
# it's a built-in function and it is used to generate
# a sequence of Integer Numbers

# a.) range(x)
# it's used to generate a sequence of Integer Numbers
# starting from zero till x-1

print (list(range(10)))

# b.) range(x,y)
# it's used to generate a sequence of Integer Numbers
# starting from x till y-1

print (list(range(10,20)))

# c.) range(x,y,stepCount/Interval)
# it's used to generate a sequence of Integer Numbers
# starting from x till y-1 based on StepCount

print (list(range(10,20,3)))

# EXERCISE : print all the even numbers till 100 using range
print(list(range(0,101,2)))

# using for and range()

for i in range(1,11):   # 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
  print (f'{i} Python')

# Take an int input from the user
# num = 13

num = int(input('Enter int number : '))
for i in range(1,11):
  print (f' {num} x {i} = {num*i}')

# Take an int input from the user
# num = 13

num = int(input('Enter Any Number : '))

for i in range(1,11):
  print(f"{num} x {i} = {num*i}")

# NESTED FOR LOOP

# recommendation system
# eg : which product to recommend to user

# OUTER LOOP WILL WAIT UNTIL INNER LOOP FINISHES THE EXECUTION

for c in ['red', 'blue', 'green']:  #outer for loop
  for v in ['car', 'bike', 'bus']:  #inner for loop
    print (c,v)

for c in ('red', 'blue', 'green'):
  for v in ('car', 'bike', 'bus'):
    print (c,v)

# while loop
# used to repeat a block of code several times
# until a certain condition is met

# syntax
# initialization           [optional]
# while condition/expression:
#   code to be executed
#   increment / decrement  [optional]

# WHIILE WILL CHECK THE CONDITION FIRST
# IF THE CONDITION IS TRUE, WHILE WILL EXECUTE ITS BODY
# AFTER WHILE FINISH EXECUTING THE BODY, CONDITION WILL BE CHECKED AGAIN
# IF THE CONDITION IS TRUE, WHILE WILL AGAIN EXECUTE ITS BODY

i = 1                  # 1ST ITER  i = 1    2ND ITER  i = 2     3RD ITER  i = 3   4TH ITER
while i<=3:            # 1<=3 (t)            2<=3 (t)            3<=3 (t)         4<=3 (FALSE)
    print(i)           # 1                   2                   3
    i = i + 1          # i = 1 + 1 ==> 2     i = 2 + 1 ==> 3     i = 3 + 1 ==> 4

# PRINT MATHEMATICAL TABLE OF A NUMBER 13
# USING WHILE LOOP

i = 1
while i <= 10:
  print (f'13 x {i} = {13*i}')
  i = i + 1

  #OR

num = 13
i = 1
while i <= 10:
  print (f'{num} x {i} = {num*i}')
  i = i + 1

# DIFFERENCES BETWEEN FOR LOOP AND WHILE LOOP
# use for loop when the number of iterations are fixed
# or use for loop when you are looking for performing an iteration

# USE WHILE LOOP WHEN THE NUMBER OF ITERATIONS ARE NOT FIXED
# WHEN THE NUMBER OF ITERATIONS ARE NOT KNOWN